# Generated by Django 5.0.7 on 2024-08-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummarizedAccidentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.IntegerField()),
                ('suburb', models.CharField(max_length=100)),
                ('place_id', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('severity_1', models.IntegerField()),
                ('severity_2', models.IntegerField()),
                ('severity_3', models.IntegerField()),
                ('severity_4', models.IntegerField()),
            ],
            options={
                'db_table': 'Summarized_Accident_Data_with_Suburb_Info',
            },
        ),
    ]
